# Generated by Django 5.2.7 on 2025-10-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appointment_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('', 'Not Assigned'), ('receptionist', 'Receptionist'), ('dentist', 'Dentist')], default='', max_length=20),
        ),
    ]
