# Generated by Django 5.2.7 on 2025-10-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_role'),
    ]

    operations = [
    ]
