# Generated by Django 5.2.7 on 2025-10-20 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_passwordresettoken_dentistnotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('missed', 'Missed'), ('reschedule_requested', 'Reschedule Requested'), ('cancel_requested', 'Cancel Requested')], default='confirmed', max_length=25),
        ),
        migrations.CreateModel(
            name='AppointmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_appointment', 'New Appointment'), ('reschedule_request', 'Reschedule Request'), ('cancel_request', 'Cancel Request'), ('appointment_cancelled', 'Appointment Cancelled')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_notifications', to='api.appointment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment Notification',
                'verbose_name_plural': 'Appointment Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
