# Generated by Django 5.2.7 on 2025-10-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_appointment_status_appointmentnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('missed', 'Missed'), ('reschedule_requested', 'Reschedule Requested'), ('cancel_requested', 'Cancel Requested')], default='confirmed', max_length=25),
        ),
    ]
