-- MySQL Script generated by MySQL Workbench
-- Tue Oct 28 10:08:14 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`api_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_user` (
  `id` INT NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `last_login` TIMESTAMP NOT NULL,
  `is_superuser` TINYINT NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `is_staff` TINYINT NULL DEFAULT NULL,
  `is_active` TINYINT NULL DEFAULT NULL,
  `date_joined` TIMESTAMP NOT NULL,
  `user_type` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `birthday` DATE NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `profile_picture` VARCHAR(255) NULL DEFAULT NULL,
  `is_active_patient` TINYINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  `is_archived` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_service` (
  `id` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `category` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_appointment` (
  `id` INT NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `time` TIME NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `dentist_id` INT NULL DEFAULT NULL,
  `patient_id` INT NULL DEFAULT NULL,
  `service_id` INT NULL DEFAULT NULL,
  `reschedule_date` DATE NULL DEFAULT NULL,
  `reschedule_dentist_id` INT NULL DEFAULT NULL,
  `reschedule_notes` TEXT NULL DEFAULT NULL,
  `reschedule_service_id` INT NULL DEFAULT NULL,
  `reschedule_time` TIME NULL DEFAULT NULL,
  `cancel_reason` TEXT NULL DEFAULT NULL,
  `cancel_requested_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`dentist_id` ASC) VISIBLE,
  INDEX (`patient_id` ASC) VISIBLE,
  INDEX (`service_id` ASC) VISIBLE,
  INDEX (`reschedule_dentist_id` ASC) VISIBLE,
  INDEX (`reschedule_service_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`dentist_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`api_service` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`reschedule_dentist_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`reschedule_service_id`)
    REFERENCES `mydb`.`api_service` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_appointmentnotification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_appointmentnotification` (
  `id` INT NULL DEFAULT NULL,
  `notification_type` VARCHAR(255) NULL DEFAULT NULL,
  `message` TEXT NULL DEFAULT NULL,
  `is_read` TINYINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `appointment_id` INT NULL DEFAULT NULL,
  `recipient_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`appointment_id` ASC) VISIBLE,
  INDEX (`recipient_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`appointment_id`)
    REFERENCES `mydb`.`api_appointment` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`recipient_id`)
    REFERENCES `mydb`.`api_user` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_billing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_billing` (
  `id` INT NULL DEFAULT NULL,
  `amount` DECIMAL NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `soa_file` VARCHAR(255) NULL DEFAULT NULL,
  `paid` TINYINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `appointment_id` INT NULL DEFAULT NULL,
  `created_by_id` INT NULL DEFAULT NULL,
  `patient_id` INT NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`appointment_id` ASC) VISIBLE,
  INDEX (`created_by_id` ASC) VISIBLE,
  INDEX (`patient_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`appointment_id`)
    REFERENCES `mydb`.`api_appointment` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`created_by_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`api_user` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_clinicalnote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_clinicalnote` (
  `id` INT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `appointment_id` INT NULL DEFAULT NULL,
  `author_id` INT NULL DEFAULT NULL,
  `patient_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`appointment_id` ASC) VISIBLE,
  INDEX (`author_id` ASC) VISIBLE,
  INDEX (`patient_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`appointment_id`)
    REFERENCES `mydb`.`api_appointment` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`api_user` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_cliniclocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_cliniclocation` (
  `id` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `latitude` DECIMAL NULL DEFAULT NULL,
  `longitude` DECIMAL NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_dentalrecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_dentalrecord` (
  `id` INT NULL DEFAULT NULL,
  `treatment` TEXT NULL DEFAULT NULL,
  `diagnosis` TEXT NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `appointment_id` INT NULL DEFAULT NULL,
  `created_by_id` INT NULL DEFAULT NULL,
  `patient_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`appointment_id` ASC) VISIBLE,
  INDEX (`created_by_id` ASC) VISIBLE,
  INDEX (`patient_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`appointment_id`)
    REFERENCES `mydb`.`api_appointment` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`created_by_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`api_user` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_dentistnotification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_dentistnotification` (
  `id` INT NULL DEFAULT NULL,
  `notification_type` VARCHAR(255) NULL DEFAULT NULL,
  `message` TEXT NULL DEFAULT NULL,
  `is_read` TINYINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `appointment_id` INT NULL DEFAULT NULL,
  `dentist_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`appointment_id` ASC) VISIBLE,
  INDEX (`dentist_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`appointment_id`)
    REFERENCES `mydb`.`api_appointment` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`dentist_id`)
    REFERENCES `mydb`.`api_user` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_document` (
  `id` INT NULL DEFAULT NULL,
  `document_type` VARCHAR(255) NULL DEFAULT NULL,
  `file` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `uploaded_at` TIMESTAMP NOT NULL,
  `patient_id` INT NULL DEFAULT NULL,
  `uploaded_by_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`patient_id` ASC) VISIBLE,
  INDEX (`uploaded_by_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`uploaded_by_id`)
    REFERENCES `mydb`.`api_user` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_fileattachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_fileattachment` (
  `id` INT NULL DEFAULT NULL,
  `file` VARCHAR(255) NULL DEFAULT NULL,
  `file_type` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `file_size` INT NULL DEFAULT NULL,
  `uploaded_at` TIMESTAMP NOT NULL,
  `patient_id` INT NULL DEFAULT NULL,
  `uploaded_by_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`patient_id` ASC) VISIBLE,
  INDEX (`uploaded_by_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`uploaded_by_id`)
    REFERENCES `mydb`.`api_user` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_inventoryitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_inventoryitem` (
  `id` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `category` VARCHAR(255) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `min_stock` INT NULL DEFAULT NULL,
  `supplier` VARCHAR(255) NULL DEFAULT NULL,
  `cost` DECIMAL NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_passwordresettoken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_passwordresettoken` (
  `id` INT NULL DEFAULT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `expires_at` TIMESTAMP NOT NULL,
  `is_used` TINYINT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`user_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`api_user` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_patientintakeform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_patientintakeform` (
  `id` INT NULL DEFAULT NULL,
  `allergies` TEXT NULL DEFAULT NULL,
  `current_medications` TEXT NULL DEFAULT NULL,
  `medical_conditions` TEXT NULL DEFAULT NULL,
  `previous_dental_treatments` TEXT NULL DEFAULT NULL,
  `emergency_contact_name` VARCHAR(255) NULL DEFAULT NULL,
  `emergency_contact_phone` VARCHAR(255) NULL DEFAULT NULL,
  `emergency_contact_relationship` VARCHAR(255) NULL DEFAULT NULL,
  `insurance_provider` VARCHAR(255) NULL DEFAULT NULL,
  `insurance_policy_number` VARCHAR(255) NULL DEFAULT NULL,
  `dental_concerns` TEXT NULL DEFAULT NULL,
  `preferred_dentist` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `filled_by_id` INT NULL DEFAULT NULL,
  `patient_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`filled_by_id` ASC) VISIBLE,
  INDEX (`patient_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`filled_by_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`api_user` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_staffavailability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_staffavailability` (
  `id` INT NULL DEFAULT NULL,
  `day_of_week` INT NULL DEFAULT NULL,
  `is_available` TINYINT NULL DEFAULT NULL,
  `start_time` TIME NULL DEFAULT NULL,
  `end_time` TIME NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `staff_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`staff_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`staff_id`)
    REFERENCES `mydb`.`api_user` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_teethimage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_teethimage` (
  `id` INT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `is_latest` TINYINT NULL DEFAULT NULL,
  `uploaded_at` TIMESTAMP NOT NULL,
  `patient_id` INT NULL DEFAULT NULL,
  `uploaded_by_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`patient_id` ASC) VISIBLE,
  INDEX (`uploaded_by_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`uploaded_by_id`)
    REFERENCES `mydb`.`api_user` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_toothchart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_toothchart` (
  `id` INT NULL DEFAULT NULL,
  `chart_data` TEXT NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `patient_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`patient_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`api_user` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_treatmentplan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_treatmentplan` (
  `id` INT NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `created_by_id` INT NULL DEFAULT NULL,
  `patient_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`created_by_id` ASC) VISIBLE,
  INDEX (`patient_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`created_by_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`api_user` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_treatmentassignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_treatmentassignment` (
  `id` INT NULL DEFAULT NULL,
  `treatment_name` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `date_assigned` TIMESTAMP NOT NULL,
  `scheduled_date` DATE NULL DEFAULT NULL,
  `completed_date` DATE NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `assigned_by_id` INT NULL DEFAULT NULL,
  `assigned_dentist_id` INT NULL DEFAULT NULL,
  `patient_id` INT NULL DEFAULT NULL,
  `treatment_plan_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`assigned_by_id` ASC) VISIBLE,
  INDEX (`assigned_dentist_id` ASC) VISIBLE,
  INDEX (`patient_id` ASC) VISIBLE,
  INDEX (`treatment_plan_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`assigned_by_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`assigned_dentist_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`treatment_plan_id`)
    REFERENCES `mydb`.`api_treatmentplan` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_group` (
  `id` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_user_groups` (
  `id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `group_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`user_id` ASC) VISIBLE,
  INDEX (`group_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`auth_group` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`django_content_type` (
  `id` INT NULL DEFAULT NULL,
  `app_label` VARCHAR(255) NULL DEFAULT NULL,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_permission` (
  `id` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `content_type_id` INT NULL DEFAULT NULL,
  `codename` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`content_type_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`content_type_id`)
    REFERENCES `mydb`.`django_content_type` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`api_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api_user_user_permissions` (
  `id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `permission_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`user_id` ASC) VISIBLE,
  INDEX (`permission_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`api_user` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`permission_id`)
    REFERENCES `mydb`.`auth_permission` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_group_permissions` (
  `id` INT NULL DEFAULT NULL,
  `group_id` INT NULL DEFAULT NULL,
  `permission_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`group_id` ASC) VISIBLE,
  INDEX (`permission_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`auth_group` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`permission_id`)
    REFERENCES `mydb`.`auth_permission` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`authtoken_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`authtoken_token` (
  `key` VARCHAR(255) NULL DEFAULT NULL,
  `created` TIMESTAMP NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`key`),
  INDEX (`user_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`api_user` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`django_admin_log` (
  `id` INT NULL DEFAULT NULL,
  `action_time` TIMESTAMP NOT NULL,
  `object_id` TEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(255) NULL DEFAULT NULL,
  `action_flag` INT NULL DEFAULT NULL,
  `change_message` TEXT NULL DEFAULT NULL,
  `content_type_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`content_type_id` ASC) VISIBLE,
  INDEX (`user_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`content_type_id`)
    REFERENCES `mydb`.`django_content_type` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`api_user` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`django_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`django_migrations` (
  `id` INT NULL DEFAULT NULL,
  `app` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `applied` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`django_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`django_session` (
  `session_key` VARCHAR(255) NULL DEFAULT NULL,
  `session_data` TEXT NULL DEFAULT NULL,
  `expire_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`session_key`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
